name: myapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  smooth_star_rating_null_safety: ^1.0.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.1
  sembast: ^3.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dwds: ^24.1.0 

flutter:

  uses-material-design: true
